# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

def default_pods
	pod 'surveymonkey-ios-sdk', '~> 1.0'
end

target ‘SurveyMonkey’ do
  default_pods
end
